/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jayce_jni_JniUtils */

#ifndef _Included_com_jayce_jni_JniUtils
#define _Included_com_jayce_jni_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jayce_jni_JniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jayce_jni_JniUtils_getCLanguageString
  (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_jayce_jni_JniUtils_sayHello
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
